[project]
name = "bosonicplus"
version = "2024.11.04"
description = "Working extension of strawberryfields bosonic backend"
dependencies = [
	"numpy",
	"scipy",
	"mpmath",
	"thewalrus",
	"matplotlib"
	]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
