[project]
name = "bosonicplus"
version = "2024.08.27"
description = "Working extension of strawberryfields bosonic backend"
dependencies = [
	"numpy",
	"scipy==1.9.3",
	"mpmath",
	"strawberryfields",
	"matplotlib"
	]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
